services:

  caddy:
    image: caddy:2.11-alpine
    environment:
      - SITE_ADDRESS=${SITE_ADDRESS}
    cap_add:
      - NET_ADMIN
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - $PWD/caddy:/etc/caddy
      - $PWD/website:/srv
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - caddy_net

  ntfy:
    image: binwiederhier/ntfy:v2.23
    command: serve
    environment:
      - TZ=Europe/Berlin
    volumes:
      - ntfy_cache:/var/cache/ntfy
      - $PWD/ntfy:/etc/ntfy
    ports:
      - 8080:80
    networks:
      - caddy_net
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 60s
        max_attempts: 3
        window: 120s

  victoriametrics:
    image: victoriametrics/victoria-metrics:v1.144.0
    ports:
      - "8428:8428"
    volumes:
      - victoriametrics_data:/storage
    command:
      - "--storageDataPath=/storage"
      - "--retentionPeriod=1"
    networks:
      - caddy_net
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 60s
        max_attempts: 3
        window: 120s
      placement:
        constraints:
          - node.role == manager

volumes:
  caddy_data:
  caddy_config:
  ntfy_cache:
  victoriametrics_data:

networks:
  caddy_net:
    driver: overlay
