services:

  pwa:
    image: ghcr.io/das-habitat/giesbert/pwa:latest
    environment:
      - SITE_ADDRESS=${SITE_ADDRESS}
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - caddy_net
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
        failure_action: rollback
        monitor: 90s
      rollback_config:
        parallelism: 1
        delay: 10s
        failure_action: pause
        monitor: 90s
      restart_policy:
        condition: on-failure
        delay: 60s
        max_attempts: 3
        window: 120s
      labels:
        - shepherd.enable=true

  server:
    image: ghcr.io/das-habitat/giesbert/server:latest
    env_file:
      - .env.deploy
    networks:
      - caddy_net
      - server_net
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
        failure_action: rollback
        monitor: 90s
      rollback_config:
        parallelism: 1
        delay: 10s
        failure_action: pause
        monitor: 90s
      restart_policy:
        condition: on-failure
        delay: 60s
        max_attempts: 3
        window: 120s
      labels:
        - shepherd.enable=true

  db:
    image: postgres:18
    volumes:
      - giesbert-db:/var/lib/postgresql
    env_file:
      - .env.deploy
    networks:
      - server_net
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 60s
        max_attempts: 3
        window: 120s

  shepherd:
    image: containrrr/shepherd:v1.8.1
    environment:
      - SLEEP_TIME=1440m
      - WITH_REGISTRY_AUTH=true
      - ROLLBACK_ON_FAILURE=true
      - FILTER_SERVICES=label=shepherd.enable=true
      - IGNORELIST_SERVICES=giesbert_db giesbert_shepherd
      - REGISTRY_USER=${REGISTRY_USER}
      - REGISTRY_HOST=ghcr.io
    secrets:
      - shepherd_registry_password
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: on-failure
        delay: 60s
        max_attempts: 3
        window: 120s

volumes:
  giesbert-db:
  caddy_data:
  caddy_config:

networks:
  caddy_net:
    driver: overlay
  server_net:
    driver: overlay
    internal: true

secrets:
  shepherd_registry_password:
    external: true
